name = "GroundHeatExchangerSizing"
uuid = "c69f955c-e283-4c57-b28d-9686908aa4bd"
version = "1.0.0-DEV"
authors = ["Gabriel-Dion <dion.gabriel100@gmail.com>"]

[deps]
BoreholeResistance = "e68eaff3-538a-4178-bf62-7dbf06caf399"
GroundHeatExchanger = "bd8f68b8-2a15-4d14-8bb6-4cefce65f0ac"
GroundResponse = "4e068bfd-c84d-4e7d-af33-179ff9550968"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[sources]
BoreholeResistance = {path = "..\\BoreholeResistance.jl"}
GroundHeatExchanger = {path = "..\\GroundHeatExchanger.jl"}
GroundResponse = {path = "..\\GroundResponse.jl"}

[compat]
Optim = "1, 2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
