[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BoreholeResistance = "e68eaff3-538a-4178-bf62-7dbf06caf399"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
GroundHeatExchanger = "bd8f68b8-2a15-4d14-8bb6-4cefce65f0ac"
GroundHeatExchangerSizing = "c69f955c-e283-4c57-b28d-9686908aa4bd"
GroundResponse = "4e068bfd-c84d-4e7d-af33-179ff9550968"

[sources]
BoreholeResistance = {path = "..\\..\\BoreholeResistance.jl"}
GroundHeatExchanger = {path = "..\\..\\GroundHeatExchanger.jl"}
GroundHeatExchangerSizing = {path = ".."}
GroundResponse = {path = "..\\..\\GroundResponse.jl"}

[compat]
BenchmarkTools = "1"
CairoMakie = "0.15"
julia = "1.12"
